### PR TITLE
Branch post pe ug

### LINKED ISSUE #213: [PE-D][Tester C] Preceding space allowed for certain inputs in name only
If I were to do `add_member n/tag/John Doe r/4-3-301 t/3efqfqef tag/logistics`, this is a valid input that will return a person with a name `tag/John Doe`, but if I do instead `add_member n/        tag/John Doe r/4-3-301 t/3efqfqef tag/logistics`, it will throw an error as seen in image below. However, if I do add_member n/        John Doe r/4-3-301 t/johndoe123 tag/logistics`, it does add in a person with the name John Doe. Seems to have certain inconsistencies with what is an acceptable name input, could be clarified in the User Guide too. Suggestion is to just not allow the slashes in the input name as I think this will create problems.

As this is my final bug report for this, just want to say overall I think yall did a good job and it is great that most of the commands are designed simple enough for any user to follow along and use. The adding of sessions, tele handles, tags also make the UI very colourful which is nice. Hope my bug reports were helpful to some extent and all the best for your actual practical!

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nws321/ped#13

### LINKED ISSUE #217: [PE-D][Tester B] Not updated command summary
The `add_session`, `find_sessions`, `delete_session` are not present in the command summary which I think should be added.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: SwaminathanViswa/ped#8

### PR DESCRIPTION
**Pull request by keithxun**
Fix #213 - Add notes in UG
Fix #217 - Updated command summary

### CODE REVIEW

**Comment by keithxun** [comment]
fix #209 #208

**Comment by keithxun** [comment]
Fix #207

**Comment by keithxun** [comment]
Fix #203

**Comment by keithxun** [comment]
Fix #202

**Comment by keithxun** [comment]
Fix #198

**Comment by keithxun** [comment]
Fix #184

**Comment by keithxun** [comment]
Fix #170

**Comment by taggyhan** [comment]
great work

**Review by taggyhan — APPROVED** [review]
LGTM

**Pull request merged**
